services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: card-kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-init:
    image: apache/kafka:3.7.0
    container_name: card-kafka-init
    depends_on:
      - kafka
    command: >
      bash -c "
      echo 'Aguardando Kafka iniciar...' &&
      sleep 25 &&

      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic card.proposal.received --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic card.proposal.rejected --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic card.proposal.completed --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic card.account.created --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic card.benefits.activated --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&

      echo 'Tópicos criados com sucesso.'
      "

  redis:
    image: redis:7-alpine
    container_name: card-redis
    ports:
      - "6379:6379"

  proposal-postgres:
    image: postgres:16-alpine
    container_name: proposal-postgres
    environment:
      POSTGRES_DB: proposal_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  eligibility-postgres:
    image: postgres:16-alpine
    container_name: eligibility-postgres
    environment:
      POSTGRES_DB: eligibility_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  card-account-postgres:
    image: postgres:16-alpine
    container_name: card-account-postgres
    environment:
      POSTGRES_DB: card_account_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"

  benefit-postgres:
    image: postgres:16-alpine
    container_name: benefit-postgres
    environment:
      POSTGRES_DB: benefit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"

  audit-postgres:
    image: postgres:16-alpine
    container_name: audit-postgres
    environment:
      POSTGRES_DB: audit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"

  # eligibility-service:
  #   build:
  #     context: .
  #     dockerfile: eligibility-service/Dockerfile
  #   container_name: eligibility-service
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://eligibility-postgres:5432/eligibility_db
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   depends_on:
  #     - eligibility-postgres
  #     - kafka

  # card-account-service:
  #   build:
  #     context: .
  #     dockerfile: card-account-service/Dockerfile
  #   container_name: card-account-service
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://card-account-postgres:5432/card_account_db
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   depends_on:
  #     - card-account-postgres
  #     - kafka

  # benefit-service:
  #   build:
  #     context: .
  #     dockerfile: benefit-service/Dockerfile
  #   container_name: benefit-service
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://benefit-postgres:5432/benefit_db
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   depends_on:
  #     - benefit-postgres
  #     - kafka

  # proposal-service:
  #   build:
  #     context: .
  #     dockerfile: proposal-service/Dockerfile
  #   container_name: proposal-service
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://proposal-postgres:5432/proposal_db
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #     ELIGIBILITY_URL: http://eligibility-service:8081
  #     CARD_ACCOUNT_URL: http://card-account-service:8082
  #     BENEFIT_URL: http://benefit-service:8083
  #   depends_on:
  #     - proposal-postgres
  #     - redis
  #     - kafka
  #     - eligibility-service
  #     - card-account-service
  #     - benefit-service

  # audit-service:
  #   build:
  #     context: .
  #     dockerfile: audit-service/Dockerfile
  #   container_name: audit-service
  #   ports:
  #     - "8085:8085"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://audit-postgres:5432/audit_db
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   depends_on:
  #     - audit-postgres
  #     - kafka

  # notification-service:
  #   build:
  #     context: .
  #     dockerfile: notification-service/Dockerfile
  #   container_name: notification-service
  #   ports:
  #     - "8084:8084"
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   depends_on:
  #     - kafka
